id = "renpy"
name = "Ren'Py"
version = "0.2.0"
schema_version = 1
authors = ["ZeynTheDev"]
description = "Ren'Py language support for Zed"
repository = "https://github.com/ZeynTheDev/zed-renpy-extension"

[grammars.renpy]
repository = "https://github.com/ZeynTheDev/tree-sitter-renpy"
rev = "daa8c1a9b2b1b85f2b9c12b3cc0f0fe223474b82"
